### ISSUE TITLE
X12

### ISSUE THREAD

**Issue by homer8173** [php-edifact/edifact#109]
Hello
i know i m out of context
but one of my prospect want  to talk with US in X12 and all my software are done in PHP-EDIFACT
Do you know an easy way to proceed ?
BR,
Norbert

**Comment by sabas** [comment]
Hi, there are different people who asked over the years for x12 but I never used it as I don't talk with US partners :)
From my understanding you need to change the separators but the logic should be the same.
UN/EDIFACT is open for specifications, X12 not...
Do you need to parse existing messages or encode or both?
First we need to improve Parser.php and Encoder.php so that they can work with X12.

**Comment by homer8173** [comment]
Thanks for you interest, I have a full set to exchange, orders, modifications, invoices and desadv
There is more or less all 50% of my software to adapt

**Comment by homer8173** [comment]
I'm not sure to have the project because I'm far from the result.
An option is to use a translator but it will be expensive

**Comment by homer8173** [comment]
I gave to this prospect our situation and I'm waiting for their response but yes it seems doable to read those messages
