### ISSUE TITLE
Which mapping file to use?

### ISSUE THREAD

**Issue by sburkett** [php-edifact/edifact#77]
More of a question than an issue - sorry!

I am trying to parse some 271 Health Care Eligibility Benefit Response files, but I am not sure which mapping file I should be using from the edifact-mapping package. I am NOT an EDI expert by any stretch of the imagination. Just trying to get this data into JSON format so I can work with it. Any guidance or advice would be greatly appreciated!

**Comment by sabas** [comment]
Hi Scott,
they're ANSI edi files, not UN/CEFACT. I never tried to parse/use the american standard mostly because of the lack of proper documentation / mappings :-)
I imagine that you can try at least to work with the Parser to split the message in a proper array. The main difference I think is on the separators (* instead of + and so on).

**Comment by sburkett** [comment]
I believe you are right .... damn! Thanks for the followup. I'll see what I can do with it.

**Comment by sabas** [comment]
If you succeed please let us know, in the past some people asked for guidance as well!
